export default [
  {
    id: 1,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic1.jpg'),
  },
  {
    id: 2,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic2.jpg'),
  },
  {
    id: 3,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic3.jpg'),
  },
  {
    id: 4,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic4.jpg'),
  },
  {
    id: 5,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic5.jpg'),
  },
  {
    id: 6,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic6.jpg'),
  },
  {
    id: 7,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic7.jpg'),
  },
  {
    id: 8,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic1.jpg'),
  },
  {
    id: 9,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic8.jpg'),
  },
  {
    id: 10,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic9.jpg'),
  },
  {
    id: 11,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic10.jpg'),
  },
  {
    id: 12,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic11.jpg'),
  },
  {
    id: 13,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic12.jpg'),
  },
  {
    id: 14,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic13.jpg'),
  },
  {
    id: 15,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic2.jpg'),
  },
  {
    id: 16,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic5.jpg'),
  },
  {
    id: 17,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic1.jpg'),
  },
  {
    id: 18,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic7.jpg'),
  },
  {
    id: 19,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic10.jpg'),
  },
  {
    id: 20,
    title: 'lorem ipsum dolor set amet consctur',
    price: '24.07',
    type: 'item',
    photo: require('./assets/pic9.jpg'),
  },
];
